xcan:
  trace:
    enabled: true
  datasource:
    extra:
      dbType: '@databaseType@'
      entityPackages:
        - cloud.xcan.angus.idgen.entity
        - cloud.xcan.angus.core.storage.domain
    hikari:
      readOnly: false
      connectionTestQuery: SELECT 1 FROM DUAL
      # Pool name
      poolName: xcanHikariCP
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 30
      minimumIdle: 10
    mysql:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://${STORAGE_MYSQL_HOST}:${STORAGE_MYSQL_PORT}/${STORAGE_MYSQL_DB}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=${info.app.timezone}&rewriteBatchedStatements=true
      username: ${STORAGE_MYSQL_USER}
      password: ${STORAGE_MYSQL_PASSWORD}
      schema:
        - mysql/idgen-schema.sql
    postgresql:
      driverClassName: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:postgresql://${STORAGE_POSTGRES_HOST}:${STORAGE_POSTGRES_PORT}/${STORAGE_POSTGRES_DB}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=${info.app.timezone}&rewriteBatchedStatements=true
      username: ${STORAGE_POSTGRES_USER}
      password: ${STORAGE_POSTGRES_PASSWORD}
      schema:
        - postgres/idgen-schema.sql
    commonlink:
      mysql:
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://${COMMON_MYSQL_HOST}:${COMMON_MYSQL_PORT}/${COMMON_MYSQL_DB}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=${info.app.timezone}&rewriteBatchedStatements=true
        username: ${COMMON_MYSQL_USER}
        password: ${COMMON_MYSQL_PASSWORD}
      postgresql:
        driverClassName: org.postgresql.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://${COMMON_POSTGRES_HOST}:${COMMON_POSTGRES_PORT}/${COMMON_POSTGRES_DB}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=${info.app.timezone}&rewriteBatchedStatements=true
        username: ${COMMON_POSTGRES_USER}
        password: ${COMMON_POSTGRES_PASSWORD}
  storage:
    storeType: ${STORAGE_TYPE}
    proxyAddress: ${STORAGE_FILES_PROXY_ADDRESS}
    aesKey: ${STORAGE_FILES_ENCRYPTION_KEY}
    localDir: ${STORAGE_LOCAL_DIR}
    region: ${STORAGE_S3_REGION:}
    endpoint: ${STORAGE_S3_ENDPOINT}
    accessKey: ${STORAGE_S3_ACCESS_KEY}
    secretKey: ${STORAGE_S3_SECRET_KEY}
  redis:
    enabled: true
    deployment: SINGLE
    host: ${STORAGE_REDIS_HOST}
    port: ${STORAGE_REDIS_PORT}
    password: ${STORAGE_REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 5

eureka:
  client:
    healthcheck:
      enabled: true
    eureka-connection-idle-timeout-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://${GM_EUREKA_USER_NAME}:${GM_EUREKA_USER_PASSWORD}@${GM_HOST}:${GM_PORT}/eureka/
  instance:
    app-name: '@artifactId@'
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui/
    health-check-url-path: /actuator/health

spring:
  security:
    oauth2:
      resource-server:
        opaque-token:
          client-id: ${OAUTH2_INTROSPECT_CLIENT_ID}
          client-secret: ${OAUTH2_INTROSPECT_CLIENT_SECRET}
          introspection-uri: ${GM_APIS_URL_PREFIX}/oauth2/introspect
  jpa:
    hibernate:
      ddl-auto: validate
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 5
          time_zone: ${info.app.timezone}
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
        session_factory:
          statement_inspector: cloud.xcan.angus.core.jpa.interceptor.TenantInterceptor
    database: '@databaseType@'
    database-platform: '@databaseDialect@'
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

